### ISSUE TITLE
Issue with deployment to now

### ISSUE THREAD

**Issue by Marnix-IxD** [drejohnson/sapper-graphql-firebase#1]
Hi Dre,

I've been fascinated by your setup here for the past few days, learned about some new platforms like Hasura.
But I've been stuck on trying to get this to run on Now 2.
I think I've done everything needed.
My .env file contains hasura credentials etc.
I added a config.js file to the src/firebase/ folder
Successfully deployed the function to add the hasura tokens from firebase auth
And locally it works like a charm to log in and log out.

So my next step was to try and deploy it to now, and that's where I'm stuck.
I keep getting a 500 server error message, and it is complaining about modules in server.js not being found. 
Do you have any pointers on how you've gotten this to work for you?

**Comment by drejohnson** [comment]
Yeah, it's a known issue with now. I've abandoned deployment to now since it's broken, I'm currently deploying to [google cloud run](https://cloud.google.com/run/). I'll update the repo soon to reflect that.
