### ISSUE TITLE
Circular dependency warnings

### ISSUE THREAD

**Issue by atomobianco** [drejohnson/sapper-graphql-firebase#2]
Hi, and thanks for the template, very useful and well crafted!
A doubt about one thing though: I get 
```
Circular dependency: src/firebase/auth.js -> src/firebase/init.js -> src/firebase/auth.js
```

Would it be possible to move the `authListener` maybe in the `init.js` file so that it would not need circular imports?

Also, a nice to have, some comments/readme about the operations going on with the auth + forkJoin + tap + etc. for a non RxJs developer

**Comment by drejohnson** [comment]
Yes I have a fix for the `circular dependency` error. I just forgot to update this repo with it. I will also add some comments soon. 

Thanks for checking the template out!

**Comment by atomobianco** [comment]
Thanks! And by the way, this template would deserve to be referenced in those awesome-svelte or awesome-sapper pages that start to appear 😉

**Comment by atomobianco** [comment]
Hello, mind asking if there is any updates on this?

**Comment by drejohnson** [comment]
@atomobianco, I’ve made a few changes and added a few comments to explain some of the rxjs stuff. Hope it helps. Feel free to ask if you still have questions.

**Comment by atomobianco** [comment]
Thanks! I'll try this out and see how it's behaving.

Few comments that come to mind:
1. twice the line `authStore.set({ status: 'in', user, token })` in `auth.js`, one before and one after the `if (hasuraClaim) {`
2. I did not find anywhere in the readme the fact that one has to provide a `firebase/.config.js`; that might be not know by a newbie
3. the readme line 
    > Install dependencies: run `yarn` in project root"
  
    could also add for `npm`:
    > Install dependencies: run `yarn` or `npm install` in project root

**Comment by atomobianco** [comment]
the `redirectAfterLogin();` is causing a `ReferenceError: redirectAfterLogin is not defined at SafeSubscriber._next`
