### ISSUE TITLE
What's the best way to add `firestore`?

### ISSUE THREAD

**Issue by atomobianco** [drejohnson/sapper-graphql-firebase#3]
The machinery to import and use firebase is different from standard templates that one finds around, so a copy paste would not work here.

As of now, to use firestore I am obliged to instantiate a `db` variable, and assign to it the firestore instantiation with a subscription.
Here's the code:

```
import { collectionData } from 'rxfire/firestore';
import { firebaseApp$ } from '../firebase';

let db;
firebaseApp$.subscribe(firebaseApp => (db = firebaseApp.firestore()))
```

This works.
However, instead of passing through `firebaseApp$`, I would prefer to have `db` instantiated  inside `firebase/index.js` and to just import it with 

`import { db } from '../firebase'`.

How could it be done?

**Comment by jimjones26** [comment]
@atomobianco did you find an answer to this? I have been struggling with a way to workaround this for a week.

**Comment by atomobianco** [comment]
Hi @jimjones26 , still using as show above, but only to save data; I guess I'll hit new problems when retrieving data.

**Comment by drejohnson** [comment]
@atomobianco and @jimjones26 I would probably just create a function that takes the `firebaseApp$` `subject` as a parameter and then instantiate `firestore` from that parameter. If you need to pass around the `db` you can assign it to a store. Don't know your exact needs but that approach should work well. Also, my approach to lazyloading Firebase is a little unorthodox but there's no real way to lazyload Firebase and I prefer not to include Firebase's huge bundle size in my apps bundle. Here's some pseudo code to kinda give you an idea if what I'm recommending:

```
export function lazyLoad() {
  // create observable from dynamic import
  const firebase$ = from(import('firebase/app'))
  const auth$ = from(import('firebase/auth'))
  const firestore$ = from(import('firebase/firestore'))
  const rxfirestore$ = from(import('rxfire/firestore'))
  // when all observables, e.g (firebase$, auth$), complete, give the last emitted value from each as an array
  return forkJoin(firebase$, rxfirestore$, auth$, firestore$).pipe(
    ...
  )
```

```
import { writable } from 'svelte/store'
import { collectionData } from 'rxfire/firestore'
import { tap } from 'rxjs/operators'

export const cityStore = writable(null)

export const collectionData = firebaseApp => {
  const db = firebaseApp.firestore()
  const settings = {}
  db.settings(settings)
  const citiesRef = db.collection('cities')
  citiesRef.where('state', '==', 'CA')
  collectionData(citiesRef, 'id')
    .pipe(tap(cities => console.log('This is just an observable!')))
    .subscribe(cities => {
      cityStore.set(cities)
    })
}

```

You would use it the same way I'm instantiating the `authListener` function

**Comment by jimjones26** [comment]
@drejohnson thanks for the response. I had abandoned your approach to lazy loading as I did not entirely understand what was going on, but now my bundle size is pretty big, especially with rxfire added on top of firebase. I'll go back through your code and try and get a better understanding.

**Comment by atomobianco** [comment]
Doesn't this require a sort of `if ($authStore.status === "in")` somewhere to authorize the firestore request?
